/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './**/*.php',
    './*.php',
    './template-parts/**/*.php',
    './blocks/**/*.php',
  ],
  safelist: [
    // Safelist common WordPress image classes to prevent overrides
    'alignnone',
    'alignleft',
    'alignright',
    'aligncenter',
    'size-thumbnail',
    'size-medium',
    'size-large',
    'size-full',
    'wp-image',
    'wp-caption',

    // E365 Block System - Dynamic classes generated by PHP helpers

    // Spacing classes (padding/margin) - mobile
    { pattern: /^(p|m)(t|b|l|r|x|y)?-(0|4|6|8|12|16|20|24|32)$/ },
    // Spacing classes - desktop (lg: variant)
    {
      pattern: /^(p|m)(t|b|l|r|x|y)?-(0|6|8|12|16|20|24|32)$/,
      variants: ['lg'],
    },

    // Grid columns - base
    { pattern: /^grid-cols-(1|2|3|4)$/ },
    // Grid columns - responsive
    {
      pattern: /^grid-cols-(1|2|3|4)$/,
      variants: ['sm', 'md', 'lg'],
    },

    // Gap - base
    { pattern: /^gap-(0|4|6|8|12|16)$/ },
    // Gap - desktop
    {
      pattern: /^gap-(0|6|8|12|16)$/,
      variants: ['lg'],
    },

    // Flex direction - base
    { pattern: /^flex-(row|col)$/ },
    // Flex direction - desktop
    {
      pattern: /^flex-(row|col)$/,
      variants: ['lg'],
    },

    // Width fractions for column ratios
    {
      pattern: /^w-(1\/2|1\/3|2\/3|1\/4|3\/4|2\/5|3\/5)$/,
      variants: ['lg'],
    },
    'lg:w-[70%]',
    'lg:w-[30%]',

    // Text alignment and colors
    { pattern: /^text-(left|center|right)$/ },
    { pattern: /^text-(white|slate-900|slate-600|slate-500)$/ },

    // Items alignment
    { pattern: /^items-(start|center|end|stretch)$/ },

    // Justify content
    { pattern: /^justify-(start|center|end|between|around)$/ },

    // Flex wrap
    'flex-wrap',

    // Order (for mobile column reordering)
    'order-1',
    'order-2',
    'lg:order-1',
    'lg:order-2',

    // Aspect ratios
    'aspect-video',
    'aspect-square',
    'aspect-[4/3]',
    'aspect-[9/16]',
    'aspect-[3/2]',
    'aspect-[2/3]',

    // Container widths (testimonial, sections)
    'max-w-[720px]',
    'max-w-[960px]',
    'max-w-[1280px]',
    'max-w-[1440px]',
    'max-w-full',
    'max-w-4xl',

    // Common utility classes used in blocks
    'w-full',
    'h-full',
    'relative',
    'absolute',
    'inset-0',
    'overflow-hidden',
    'rounded-lg',
    'rounded-xl',
    'cursor-pointer',
    'object-cover',
    'transition-all',
    'transition-transform',
    'transition-opacity',
    'duration-200',
    'duration-300',

    // Hover states
    'group',
    'group-hover:scale-105',
    'group-hover:scale-110',
    'group-hover:bg-black/30',

    // Background utilities
    'bg-white',
    'bg-black/20',
    'bg-black/30',
    'bg-slate-50',
    'bg-slate-100',

    // Shadow utilities
    'shadow-lg',

    // Flex utilities
    'flex',
    'inline-flex',

    // Border utilities
    'border',
    'border-2',
    'border-dashed',
    'border-slate-200',
    'border-slate-300',

    // Min height
    'min-h-[120px]',
  ],
  theme: {
    extend: {
      colors: {
        // Brand colors
        primary: '#AA1010',
        // Add more custom colors here
      },
    },
  },
  corePlugins: {
    // Disable Tailwind's preflight to avoid conflicts with WordPress styles
    preflight: false,
  },
  plugins: [],
}
